version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/homebridge:/homebridge
    environment:
      HOMEBRIDGE_CONFIG_UI : 1
      HOMEBRIDGE_CONFIG_UI_PORT: $APP_HOMEBRIDGE_PORT
